listen_addresses: 0.0.0.0:3333
postgres:
  connection_string: ${MARTIN_DATABASE_URL}
  auto_publish: false
  default_srid: 4326
  functions:
    land-context:
      schema: public
      function: land_context
